export const SET_USERS_DATA = "SET_USERS_DATA";
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_USER_INFO_LOADING = "SET_USER_INFO_LOADING";
export const SET_USER_REPOS = "SET_USER_REPOS";
